insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (18, 'Isuzu', 'coklat', 'Panther LS', '03/05/2019', 17);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (34, 'Porsche', 'hitam', 'Macan Turbo', '03/05/2019', 15);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (20, 'Toyota', 'ungu', 'Avanza G 1.3', '09/05/2019', 19);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (16, 'Audi', 'putih', 'Q7', '07/05/2019', 19);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (24, 'Nissan', 'biru', 'Grand Livina', '06/05/2019', 13);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (2, 'KIA', 'merah', 'Picanto', '04/05/2019', 17);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (11, 'Mazda', 'jingga', 'Biante', '08/05/2019', 16);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (9, 'Hyundai', 'merah', 'H-100', '08/05/2019', 19);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (32, 'Isuzu', 'jingga', 'D-Max', '05/05/2019', 12);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (31, 'Daihatsu', 'hitam', 'Ayla', '05/05/2019', 17);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (47, 'Nissan', 'hitam', 'Serena', '07/05/2019', 14);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (13, 'Chevrolet', 'putih', 'Orlando', '04/05/2019', 12);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (8, 'Peugeot', 'ungu', 'RCZ', '05/05/2019', 15);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (10, 'Isuzu', 'jingga', 'Panther Touring', '03/05/2019', 10);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (32, 'Ferrari', 'ungu', 'GTC4 Lusso T', '05/05/2019', 15);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (35, 'Volkswagen', 'jingga', 'Golf', '07/05/2019', 19);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (17, 'BMW', 'coklat', 'M5', '09/05/2019', 10);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (6, 'Lexus', 'hitam', 'GS 200t Luxury', '05/05/2019', 11);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (23, 'Porsche', 'ungu', '718 Boxster GTS', '08/05/2019', 17);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (18, 'Mercedes-Benz', 'putih', 'AMG S 63', '02/05/2019', 11);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (15, 'Hyundai', 'jingga', 'Tucson', '04/05/2019', 18);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (4, 'Mitsubishi', 'kuning', 'Outlander GLS', '04/05/2019', 16);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (30, 'Mercedes-Benz', 'merah', 'Maybach S560', '02/05/2019', 13);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (48, 'Porsche', 'biru', '911 GT2 RS', '09/05/2019', 15);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (9, 'Honda', 'kuning', 'Jazz RS', '04/05/2019', 16);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (21, 'BMW', 'hitam', 'i8 Roadster', '02/05/2019', 18);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (29, 'Ford', 'merah', 'Fiesta 1.5 Trend Sport', '08/05/2019', 20);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (32, 'Lexus', 'putih', 'GS 200t F Sport', '09/05/2019', 14);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (7, 'Toyota', 'hitam', 'Avanza', '07/05/2019', 17);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (6, 'Lexus', 'merah', 'ES 300h', '04/05/2019', 15);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (2, 'BMW', 'coklat', 'M4 Coupe', '02/05/2019', 10);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (37, 'BMW', 'kuning', '7 Series', '09/05/2019', 20);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (41, 'Honda', 'merah', 'Brio RS', '01/05/2019', 13);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (32, 'Ford', 'putih', 'Escape XLT', '02/05/2019', 18);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (46, 'KIA', 'abu-abu', 'Pregio', '07/05/2019', 20);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (14, 'BMW', 'coklat', 'X5', '04/05/2019', 15);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (22, 'Datsun', 'coklat', 'GO+', '07/05/2019', 18);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (35, 'BMW', 'abu-abu', 'Z4', '08/05/2019', 12);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (36, 'Honda', 'merah', 'HR-V 1.5L E CVT', '03/05/2019', 18);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (9, 'Ford', 'kuning', 'Escape Limited', '01/05/2019', 11);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (40, 'Land Rover', 'biru', 'Evoque', '02/05/2019', 10);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (40, 'Porsche', 'ungu', 'Cayenne Turbo S', '08/05/2019', 19);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (2, 'Ford', 'biru', 'Focus 2.0 S', '03/05/2019', 17);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (32, 'BMW', 'kuning', 'X4', '03/05/2019', 13);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (8, 'Datsun', 'putih', 'Cross', '08/05/2019', 16);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (49, 'Toyota', 'kuning', 'Corolla', '05/05/2019', 10);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (46, 'Lexus', 'merah', 'LX 570', '08/05/2019', 19);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (21, 'Ford', 'coklat', 'Fiesta 1.6 S', '01/05/2019', 18);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (29, 'Lexus', 'hitam', 'RX 200t Luxury', '02/05/2019', 12);
insert into mobil (pemilik_lama_id, merek, warna, tipe, tgl_titip, lama_titip_hari) values (20, 'Audi', 'biru', 'A4', '03/05/2019', 13);
