--view katalog mobil--
CREATE OR REPLACE VIEW katalog_mobil as
SELECT x.MOBIL_ID as ID_MOBIL, x.MEREK as MEREK, x.TIPE as TIPE, y.HARGA_JUAL as HARGA
FROM MOBIL x, PEMBELIAN y
WHERE x.MOBIL_ID=y.MOBIL_ID;

--view checkout pembelian--
CREATE OR REPLACE VIEW checkout_pembelian as
SELECT x.MOBIL_ID as ID_MOBIL, x.MEREK as MEREK, x.TIPE as TIPE, y.PEMBELIAN_ID as PEMBELIAN_ID, z.PEMBAYARAN_ID as PEMBAYARAN_ID, z.TOTAL as TOTAL
FROM MOBIL x, PEMBELIAN y, PEMBAYARAN z
WHERE x.MOBIL_ID=y.MOBIL_ID and y.PEMBELIAN_ID=z.PEMBELIAN_ID;

--View balik nama--
CREATE OR REPLACE VIEW balik_nama as
SELECT y.MOBIL_ID AS ID_MOBIL, x.NAMA AS NAMA_PEMILIK_LAMA, x.ALAMAT AS ALAMAT_PEMILIK_LAMA, x.NO_TELP AS NOMOR_TELEFON_PEMILIK_LAMA, x.JK AS JENIS_KELAMIN_PEMILIK_LAMA, z.NAMA AS NAMA_PELANGGAN, z.ALAMAT AS ALAMAT_PELANGGAN, z.NO_TELP AS NOMOR_TELEFON_PELANGGAN, z.JK AS JENIS_KELAMIN_PELANGGAN
FROM PEMILIK_LAMA x, MOBIL y, PEMBELIAN q, PELANGGAN z
WHERE x.PEMILIK_LAMA_ID=y.PEMILIK_LAMA_ID and y.MOBIL_ID=q.MOBIL_ID and q.pelanggan_id=z.pelanggan_id;

--View costumer service--
CREATE OR REPLACE VIEW costumer_service AS
SELECT x.PEGAWAI_ID AS ID_Pegawai, x.NAMA AS nama_pegawai, x.NO_TELP AS NO_TELEPON_PEGAWAI, x.JK AS Jenis_kelamin_pegawai ,z.PELANGGAN_ID AS PELANGGAN_ID ,z.NAMA AS Nama_pelanggan, z.NO_TELP AS NOMOR_TELEPON_PELANGGAN
FROM PEGAWAI x, PEMBELIAN y, PELANGGAN z
WHERE x.PEGAWAI_ID=y.PEGAWAI_ID AND y.PELANGGAN_ID=z.PELANGGAN_ID;



