--view katalog mobil
CREATE OR REPLACE VIEW katalog_mobil as
SELECT x.MOBIL_ID as ID_MOBIL, x.MEREK as MEREK, x.TIPE as TIPE, y.HARGA_JUAL as HARGA
FROM MOBIL x, PEMBELIAN y
WHERE x.MOBIL_ID=y.MOBIL_ID;

--view checkout pembelian
CREATE OR REPLACE VIEW checkout_pembelian as
SELECT x.MOBIL_ID as ID_MOBIL, x.MEREK as MEREK, x.TIPE as TIPE, y.PEMBELIAN_ID as PEMBELIAN_ID, z.PEMBAYARAN_ID as PEMBAYARAN_ID, z.TOTAL as TOTAL
FROM MOBIL x, PEMBELIAN y, PEMBAYARAN z
WHERE x.MOBIL_ID=y.MOBIL_ID and y.PEMBELIAN_ID=z.PEMBELIAN_ID;
